name: Make Scout Package Public
on:
  workflow_dispatch:
jobs:
  public:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Set public
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          gh api /orgs/macrocontent/packages/container/scout --jq '{visibility,repository:.repository.full_name}'
          echo '{"visibility":"public"}' | gh api --method PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /orgs/macrocontent/packages/container/scout \
            --input -
          gh api /orgs/macrocontent/packages/container/scout --jq .visibility
